AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for the deployment of the bikeshare ride duration prediction service.
  Docker + Lambda + API Gateway
Globals:
  Function:
    Timeout: 60

Resources:
  PredictFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 4096
      Events:
        PredictApi:
          Type: Api
          Properties:
            Path: /predict
            Method: POST
    Metadata:
      DockerTag: bikeshare-ride-duration-prediction-service-v3
      DockerContext: ./predict
      Dockerfile: Dockerfile

Outputs:
  PredictApi:
    Description: "API Gateway endpoint URL for Prod stage for Predict function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict/"
  PredictFunction:
    Description: "Prediction Lambda Function ARN"
    Value: !GetAtt PredictFunction.Arn
  PredictFunctionIamRole:
    Description: "Implicit IAM Role created for Predict function"
    Value: !GetAtt PredictFunctionRole.Arn